[workspace]
members = ["app", "infrastructure", "syservice", "tui", "view"]
[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["Crowds"]
categories = ["editor"]
repository = "https://github.com/Crowds21/rsy-scribe"

[workspace.dependencies]
thiserror = "1.0"
log = "0.4"
webbrowser="1.0.6"