[icon]
outline="󰉖 "
paragraph=" "
head1="󰉫 "
head2="󰉬 "
head3="󰉭 "
head4="󰉮 "
head5="󰉯 "
head6="󰉰 "

unordered_list="󰷐 "
ordered_list="󰉻 "
task_list="󰝖 "

quote="󱆨 "
document="󰧮 "
notes=" "

code_block=" "
table="󰓫 "