"editor.bg" = { bg = "bg" }
"editor.popup.bg" ={bg = "bg_darker"}
"editor.font" = { fg = "fg" }

# Block style
"node.heading.title" = { fg = "orange", modifier = "bold" }
"node.heading" = { fg = "orange" }
"node.quote" = { bg = "comment_bg" }
"node.list" = { fg = "fg" }

# InLineItem style
"node.blockquote" = { fg = "comment" }
"node.text.strong" = { fg = "fg", modifier = "bold" }
"node.text.italic" = { fg = "fg", modifier = "italic" }
"node.text.mark" = { bg = "highlight_yellow" }
"node.text.blockref" = { fg = "blue" }
"node.text.weblink" = { fg = "link_blue", modifier = "underlined" }
"node.text.mathblock" = { fg = "cyan" }
"node.text.code" = { fg = "green", bg = "code_bg" }
"node.text.tag" = { fg = "purple", modifier = "bold" }

# UI elements
"ui.gutter" = { fg = "gutter_fg", bg = "gutter_bg" }
"ui.gutter.DECOR" = { fg = "cyan" }
"ui.bufferline" = { bg = "blue", bg_scale = 1.0 }

[palette]
# Base colors (保持原有)
bg = "#282c34"
# 比主背景稍暗，用于区分层次
bg_darker = "#1e2127"
bg_lighter = "#323842"
fg = "#abb2bf"

red = "#e06c75"
orange = "#d19a66"
yellow = "#e5c07b"
green = "#98c379"
cyan = "#56b6c2"
blue = "#61afef"
purple = "#c678dd"
white = "#abb2bf"
black = "#282c34"
gray = "#5c6370"

highlight = "#e2be7d"
comment = "#7f848e"
link_blue = "#548af7"
code_bg = "#26292c"
comment_bg = "#2b2d30"
gutter_fg = "#4b5059"
gutter_bg = "#1e1f22"
highlight_yellow = "#f2c55c"
