"editor.bg" = { bg = "bg" }
"editor.font" = { fg = "fg" }

"node.heading.h1" ={fg="orange"}
"node.heading.h2" ={fg="orange"}
"node.heading.h3" ={fg="orange"}
"node.heading.h4" ={fg="orange"}
"node.heading.h5" ={fg="orange"}
"node.heading.h6" ={fg="orange"}

"node.blockquote" ={fg="gray"}
"node.text.strong" = {fg="gary"}
"node.text.link" ={fg="yellow"}
"node.text.linkText" ={fg="blue"}
"node.text.mathblock" ={fg="yellow"}
"node.text.codespan" ={fg="yellow"}


"ui.gutter" = { fg = "bg", bg_scale = 1.5 }
"ui.gutter.DECOR" = { fg = "cyan" }
"ui.bufferline" = { bg = "blue", bg_scale = 1.0 }
[palette]
bg = "#282c34"
fg = "#abb2bf"
red = "#e06c75"
orange = "#d19a66"
yellow = "#e5c07b"
green = "#98c379"
cyan = "#56b6c2"
blue = "#61afef"
purple = "#c678dd"
white = "#abb2bf"
black = "#282c34"
gray = "#5c6370"
highlight = "#e2be7d"
comment = "#7f848e"

