[package]
name = "app"
version.workspace = true
edition.workspace = true
authors.workspace = true
categories.workspace = true
repository.workspace = true

[dependencies]
infrastructure = { path = "../infrastructure" }
syservice = {path="../syservice"}
tui = { path = "../tui" }
view = { path = "../view" }
tokio = { version = "1.41.0", features = ["full"] }
crossterm = { version = "0.27", features = ["event-stream"] }
futures-util = { version = "0.3", features = ["std", "async-await"], default-features = false }
ratatui = "0.26"
