[package]
name = "view"
description = "UI abstractions for use in backends"
version.workspace = true
edition.workspace = true
authors.workspace = true
categories.workspace = true
repository.workspace = true

[dependencies]
syservice = {path="../syservice"}
slotmap="1.0.7"
strum = { version = "0.27.1", features = ["derive"] }
unicode-width = "0.2.0"
ratatui = "0.26"
html-escape = "0.2.13"